travis:
  secure:
    BINSTAR_TOKEN: dbjhnJ1wBwUG6aBA6dDpsRs+sJPzTb16DzmwDnkvAMpRSj3NX7qAm5mUNkwc3NFO5+TRNRLtfc5RrpmfYwa8D9BRxdaBI1fh6DmKPw7c6Scp9PLTFluFNjc+BJrggti930Uta7R2EL2GRN2AP1v+pMY42wprwtsvFPkN9zq9OhZwhM5QmGNYDlz5CuVQCrZGgLHYwpfqNp5LnKLxIIeI2YHsDrYTY7oii1WAilJEdMAsL7h3fQNtK7c+fxAXwQhuST06asx+8xv0VqTQPBwoMFZw8rhFDdVJjFd7JWleRSovQcmMMcvCnXscAupt5OTuMp8K7o1FaqUjXkHiDDGPS17Rk66CFAHXhq+NugIyd9YtyZ8LqAZgNsek52fH67mYDaAKphXhwz0qfzVGBoLz27bFARyXpzKiil9B2KE9xB7CYnZlulAq2rq+SNlPIFccWbJAQaQ3L3reaTZDg1xCmJqoHK8QW+N3LfBkYFA/UjA+8jh7swhFM/D/2FKkr1Mw6jniF2kzAD6Az4AAQoBXAgtyrZui0z5NmRGRUFD8Hx6AbmbLcTrmiGAHVsrQovKXNh9g0lAjigNsGDboZ/sFFGDw0eKCL+BPTpyTuzAeXW/zrw2Syn/o3uYUOQbRqALP2H3jiwWsyZ8+WIhpziWA7ZexLLlSoc6EV41WZvy9GcE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
