travis:
  secure:
    BINSTAR_TOKEN: ZiccoBG+xfGsZfH0ZAIa2NgPwWygKU3RdmEKj6FKPhMzxmiRf16MskNC36wGS1WwZD9xK9SRuUbcDVYAIzLo4wRMtaRPDAy6+WbxG9/kxElhUKauhP3GZaVoTEfgcucFMm9kBqU2K81hLcIAy34UMiEpNse6Vk0DWWjiGBLag/Piflgl0GjnZwtK/qpWgabN/J5UZ/QCO8BTQEfNdUQSrL5L8mXTgj4/JUePBz7LTXXNP5npJYzU0f+ooCflhN/kyhOLHFNMdm59bicehcs1VWJ+tRshtGwIwhd0crj8JyjXHWlrbvl5Tj6KV+JKWPJhlhinChwnNd/Qkroaqv5dqHZfYOwjOyjirzaos6QG8Y8j/fqUBOFXfclVaOshPyBW76GM6GOgDZt9aDpvbi3yshhVs9OzcvSn2i7znmB7BA4puEkwTye9jtmp9ktKN8LvMCyC+kwJjgCTeRfI2ZnaxRo8lDFuEL0dLM+k+YnFG9Om5NocnX01WWHgWdiT8D/k3Cs0fYUqjuadVkxfQ7AwJ6JPIjIh0iNpcv3RCvvbHuBIJ2CDD7lBt03O7j1qJ+JXV4ii/kuyrYmVVxVi23IpVUHXHlZEdDMT/G3441q7tWqmSbtWvRl3VZBAUMfZIO0yPDrzkbY+fPGEqWyuwzcXrDLC+AL5VHs8u4Cwih3KXME=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
